### ISSUE TITLE
Tiled windows are always dimmed on GNOME 45

### ISSUE THREAD

**Issue by nekohayo** [stephane-13/gnome-shell-extension-dim-background-windows#17]
Follow-up from #9:

On GNOME Shell 45.x (tested 45.2, 45.3) Wayland on Fedora 39, this feature does not seem to work. If I turn off the switch for "Apply the dimming effect to tiled windows", get two Nautilus windows open and tile them with `Super+Left` and `Super+Right`, one of them is dimmed.

This happens on both of my monitors, so  it's not just a question of primary vs secondary like #16.

**Comment by stephane-13** [comment]
Thanks for the bug report.
I've installed a Fedora 39 virtual machine and I was able to reproduce the issue.

It's related to a recent change in Gnome, which now reports tiled windows as maximized vertically or horizontally, while it was not the case with Gnome 45.2 on Ubuntu 23.10.

I've prepared a bug fix release in branch v13_gnome45, which will be submitted for review shortly.

**Comment by stephane-13** [comment]
This bug should now be fixed.
The new version has been approved and released on https://extensions.gnome.org/extension/6313/dim-background-windows/.
