### ISSUE TITLE
DIM ALSO THE WALLPAPER

### ISSUE THREAD

**Issue by JE-Amouel** [stephane-13/gnome-shell-extension-dim-background-windows#19]
hello, I am a user of your extension which I find great and very useful when, like me, we always have several windows on the desktop and we need to change windows while concentrating on my work, I have been looking for a long time an extension of this kind with a very precise idea of ​​what it could provide as possibilities, for example also darkens the screen background like a modal window displayed by gnome with the key combination ALT + F2; and also to be able to have a blurring option in addition to the one obscured by default, I notably came across blurred_wallpaper : https://github.com/bouteillerAlan/blurredwallpaper,  and feh-blur-wallpaper: https://github.com/rstacruz/feh-blur-wallpaper which are not really available under gnome 45, would it be possible to have such an option?
THANKS.

**Comment by stephane-13** [comment]
Hi,
Unfortunately the desktop is not accessible as a regular window object in Gnome 4x.
Therefore effects based on GLSL shaders - such as the dimming effect provided by this extension - can't be attached to it.

The only - bad - solution to dim the wallpaper would be to 1) read the current wallpaper file 2) dim the image with some external tool 3) generate a new wallpaper file and 4) tell Gnome to use that new wallpaper image.

This seems impractical as a new wallpaper image would have to be set each time the last window is minimized or closed, each time the first window is opened or restored and each time the wallpaper image is changed. Anyone using a slideshow ("animated") wallpaper would probably see a dark/bright flash of their desktop while the dimmed version is created and activated.

The conclusion is that - for now - it's not possible to dim the desktop / wallpaper in an efficient and acceptable manner from a Gnome extension. But I will keep an eye on future Gnome versions to see if that possibility arises.
