### ISSUE TITLE
Disable on overview mode

### ISSUE THREAD

**Issue by thi-marques** [stephane-13/gnome-shell-extension-dim-background-windows#2]
Is there an way to temporary disable it when we press Super and enter in overview mode?
It will be great to have this option on settings.

I'm really enjoying this extension, thank you.

**Comment by stephane-13** [comment]
Thank you for your feedback :smile:
It's currently not possible, but I'm looking at the feature request to add a keyboard shortcut to enable / disable the extension.
Would that be an acceptable solution for you?

**Comment by stephane-13** [comment]
The version with a shortcut to toggle the dimming is out.
While it's now possible to quickly set that effect on and off in the overview mode, I will see if I can make it automatic, so that the dimming goes away in the overview.

**Comment by stephane-13** [comment]
Version 6 will disable the dimming effect in the overview mode.
