### ISSUE TITLE
Gnome 42-44 - Fails to load on initial installation: `this.interfaceSettings` is undefined

### ISSUE THREAD

**Issue by rindeal** [stephane-13/gnome-shell-extension-dim-background-windows#21]
## Steps to reproduce:

1. Clean Gnome installation
2. Install via Gnome Extensions

## Observed behaviour:

Fails to run, Gnome Extensions says:

> `this.interfaceSettings` is undefined

## Expected behaviour

Works well immediately after installation

## Workaround

1. Enable settings in the extension settings page
2. Remove extension
3. Install the extension again

## System details

Gnome version = 44.8

**Comment by stephane-13** [comment]
I think I've fixed the issue related to the error message "this.interfaceSettings is undefined".
I've tested the fix on a Fedora 38 VM and I didn't get the error message.

Would you be able to test the updated extension?
You can use this link to download it:
https://github.com/stephane-13/gnome-shell-extension-dim-background-windows/blob/v14/dim-background-windows%40stephane-13.github.com.shell-extension.zip

You can install it locally by running this command in a terminal with your user:
`gnome-extensions install dim-background-windows@stephane-13.github.com.shell-extension.zip --force`

**Comment by stephane-13** [comment]
Fix merged and new version of the extension released.
