### ISSUE TITLE
Make compatible with Gnome 46

### ISSUE THREAD

**Issue by entodoays** [stephane-13/gnome-shell-extension-dim-background-windows#23]
At the moment, the extension is labelled as incompatible with Gnome 46. Please update.
I manually enabled the json file and it seems to work properly.

**Comment by stephane-13** [comment]
Yes, I didn't have time to test and update the extension with Gnome 46 yet.
I will do it on Ubuntu 24.04 in the coming days, now that it's been released.

**Comment by pentastich** [comment]
Hi! I tried adding "46" to the "shell-version" list in the metadata, and the extension seems to work fine. It doesn't seem like any actual code changes are needed. I thought I'd let you know!

**Comment by stephane-13** [comment]
Thanks for your feedback, that's helpful :smile:

**Comment by stephane-13** [comment]
The new version with Gnome 46 compatibility has been released.
