### ISSUE TITLE
Option to disable dim for windows side by side ?

### ISSUE THREAD

**Issue by edern-appere** [stephane-13/gnome-shell-extension-dim-background-windows#9]
Hi !

I wonder if it would be nice to have an option to disable the dim effect to windows displayed side by side. For example windows displayed on each side of the screen using the Super+Left/Right shortcut would not receive the dim effect, so that they are still legible. I don't know if this is possible since one of the two windows has the focus and the other one not... Just a suggestion.

Thanks !

**Comment by stephane-13** [comment]
It would be possible to disable the dimming effect on those windows filling the left or right parts of the screen only if they are flagged with a special status - as opposed to just moving the window in such position manually, which wouldn't make them special in any way. I will check the documentation to see if that's the case or not.

**Comment by edern-appere** [comment]
Thanks for answering quickly ! As a workaround I found that having one window set to always display on top partially solves this issue.

**Comment by stephane-13** [comment]
It would be possible to disable the dimming effect on those windows filling the left or right parts of the screen only if they are flagged with a special status - as opposed to just moving the window in such position manually, which wouldn't make them special in any way. I will check the documentation to see if that's the case or not.

**Comment by stephane-13** [comment]
Unfortunately Gnome extensions can't yet get or set the windows tiling mode.
There is some work ongoing here: https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/1395
I'm leaving this issue open until it can be implemented (and yes, it may take a while!).

**Comment by stephane-13** [comment]
Actually, I went for a hackish way to implement this, until the tiling status is exposed to extensions.

I'm checking if a window is taking the whole screen height and is aligned to the left or right screen edge, or if a window is taking the whole screen width and is aligned to the top or bottom screen edge.

This should cover all tiling possibilities currently offered by Gnome.

**Comment by stephane-13** [comment]
The extension version with this feature request (disable the dim effect on tiled windows) has just been reviewed and accepted on https://extensions.gnome.org/extension/6313/dim-background-windows/.

**Comment by edern-appere** [comment]
The solution you implemented is perfect from my user point of view ! It works flawlessly !! Thanks a lot

**Comment by nekohayo** [comment]
FWIW, on GNOME Shell 45.2 Wayland on Fedora 39, this feature does not seem to work. If I turn off the switch for "Apply the dimming effect to tiled windows", get two Nautilus windows open and tile them with `Super+Left` and `Super+Right`, one of them is dimmed.

Should a new ticket be opened for this, or should this one here be reopened?

**Comment by stephane-13** [comment]
Yes, could you please open a new issue specifically mentioning the Gnome version 45.2?

It would be helpful if you could attach a screenshot showing which of the tiled window is not dimmed as expected.

The code behind this setting is kind of a hack currently because gnome 45.x doesn't have a variable that clearly identifies a window as tiled. I have to check the window position compared to the screen edges, and I suspect that something is off with Gnome 45.2.
